version: 1
formatters:
  detailed:
    format: '%(asctime)s %(name)s %(levelname)s: %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: detailed
    stream: ext://sys.stdout
  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed
    filename: logs/saas_platform.log
    maxBytes: 10485760 # 10MB
    backupCount: 5
loggers:
  __main__:
    level: DEBUG
    handlers: [console, file]
    propagate: no
root:
  level: DEBUG
  handlers: [console, file]